name: Continuous Integration

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    paths-ignore:
      - "**/README.md"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WIFI_2GZ_SSID: dummy_ssid
  WIFI_2GZ_PASS: dummy_password
  HTTP_SENDING_ENABLED: false
  HTTP_CONSUMER_ENDPOINT_URL: http://dummy_endpoint
  TIMEZONE: UTC

jobs:
  lints:
    name: Lints (Fmt & Clippy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

  build:
    name: Build Release
    runs-on: ubuntu-latest
    needs: lints
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-src rustfmt clippy

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: Install ldproxy
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall -y ldproxy
          LDPROXY_PATH=$(which ldproxy || echo "$HOME/.cargo/bin/ldproxy")
          sudo ln -s "$LDPROXY_PATH" /usr/local/bin/ldproxy
          ldproxy --version

      - name: Build
        env:
          CARGO_LINKER: ldproxy
          PATH: ${{ github.workspace }}/.cargo/bin:/home/runner/.cargo/bin:${{ env.PATH }}
        run: cargo build --release